name: input_event
description: Dart library to process raw events from `/dev/input/event*` files in Linux.
version: 1.0.0
repository: https://github.com/smartrent/dart_input_event.git

environment:
  sdk: ^3.4.3

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
